name: RDM amd64 build CI

on:
  push:
    paths-ignore:
      #- README.md
      - LICENSE
  watch:
    types: [started]

env:
  VERSION: 2020.4
  GIT_REF: 6a635b624c2a24c98b973b7c1e7729b4d8c98976
  PYTHON_EMBEDDED_VERSION: 3.7.9
  QT_VER: 5.15.1

jobs:
  build:
    name: Build
    runs-on: windows-latest
    env:
      OUTPUT_DIR: ${{ github.workspace }}\rdm\build\windows\installer\resources
      SRC_DIR: ${{ github.workspace }}\rdm\src
      THIRDPARTY_DIR: ${{ github.workspace }}\rdm\3rdparty
      RELEASE_DIR: ${{ github.workspace }}\rdm\bin\windows\release
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          repository: uglide/RedisDesktopManager
          path: rdm
          submodules: recursive
          ref: ${{ env.GIT_REF }}

      - name: Cache Qt
        id: WindowsCacheQt
        uses: actions/cache@v1
        with:
          path: ../Qt/${{ env.QT_VER }}
          key: Qt${{ env.QT_VER }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ env.QT_VER }}
          modules: qtcharts
          cached: ${{ steps.WindowsCacheQt.outputs.cache-hit }}

      - name: Prepare build
        shell: cmd
        run: |
          cd %THIRDPARTY_DIR%
          nuget install zlib-msvc14-x64 -Version 1.2.11.7795
          cd %THIRDPARTY_DIR%\lz4\build\cmake
          cmake -G "Visual Studio 16 2019" -A x64 -DLZ4_BUNDLED_MODE=on -DBUILD_SHARED_LIBS=on --build .
          cmake --build . --config "Release"
          cd %THIRDPARTY_DIR%\qredisclient\3rdparty\hiredis
          git apply ..\hiredis-win.patch
          mklink /d "C:\Python37-x64" "C:\hostedtoolcache\windows\python\%PYTHON_EMBEDDED_VERSION%\x64"
      - name: Build
        shell: cmd
        working-directory: ${{ env.SRC_DIR }}
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          lrelease rdm.pro
          qmake rdm.pro CONFIG+=release VERSION+=%VERSION%
          nmake /S /NOLOGO release
          copy %RELEASE_DIR%\rdm.exe %OUTPUT_DIR%
          xcopy resources\translations\*.qm %OUTPUT_DIR%\translations /s /i
      - name: Create package
        shell: cmd
        working-directory: ${{ env.OUTPUT_DIR }}
        run: |
          xcopy %SRC_DIR%\py . /s /i
          mkdir Lib\site-packages
          pip3 install --upgrade pip wheel
          pip3 install -t Lib\site-packages -r requirements.txt
          python -m compileall -b .
          del /s /q *.py requirements.txt
          forfiles /p "." /s /m __pycache__ /c "cmd /c if @isdir==TRUE rd /s /q @file 2>nul" 2>nul | exit /b 0
          forfiles /p "." /s /m *.dist-info /c "cmd /c if @isdir==TRUE rd /s /q @file 2>nul" 2>nul | exit /b 0
          forfiles /p "." /s /m *.egg-info /c "cmd /c if @isdir==TRUE rd /s /q @file 2>nul" 2>nul | exit /b 0
          forfiles /p "." /s /m tests /c "cmd /c if @isdir==TRUE rd /s /q @file 2>nul" 2>nul | exit /b 0
          C:\msys64\usr\bin\wget "https://www.python.org/ftp/python/%PYTHON_EMBEDDED_VERSION%/python-%PYTHON_EMBEDDED_VERSION%-embed-amd64.zip"
          7z.exe x python-%PYTHON_EMBEDDED_VERSION%-embed-amd64.zip python37.zip python37.dll unicodedata.pyd _bz2.pyd
          del python-%PYTHON_EMBEDDED_VERSION%-embed-amd64.zip
          windeployqt --no-angle --no-opengl-sw --no-compiler-runtime --no-translations --release --force --qmldir %SRC_DIR%/qml rdm.exe
          makensis.exe /V1 /DVERSION=%VERSION%.0 ../installer.nsi
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          #tag_name: ${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}-${{ github.run_id }}
          release_name: ${{ env.VERSION }}-${{ github.run_id }}
          body: |
            RDM Windows ${{ env.VERSION }}-${{ github.run_id }}
      - name: Upload release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: rdm/build/windows/installer/redis-desktop-manager-${{ env.VERSION }}.0.exe
          asset_name: redis-desktop-manager-${{ env.VERSION }}.exe
          asset_content_type: application/vnd.microsoft.portable-executable
